### ISSUE TITLE
Define a struct for patients

### ISSUE THREAD

**Issue by fav0u** [FHTW-HWSE/projekt-gruppe4-hospital#1]
Defining a struct for patients with the following attributes

- First Name
- Last Name
- Date of Birth
- Social security number
- Telefon number /Email adress

**Comment by MartinMosbeck** [comment]
Hi, just writing this for this one task, but it applies for all the ones you have added up till now.

Tasks should not be just a rehashing of the requirements. While requirements should not include implementation details, tasks should be more tangible, small portions that can be implemented and verified, and can contain implementation details.

For example I see multiple tasks that are a precursor, subtask here:
- Implement queues to store patients
- Define struct for a user with the following content:...
- Implement function to add a user to a queue
- Implement function that given all queues decides which patient to treat next...
...

Additionally if you need a starting point, tasks should rather arise from userstories than requirements.

Best,
Martin
